/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Study Css Effect",
  "description": "这是一个用来学习css特效的项目，旨在学习和收集一些特别的动画特效为网站交互增色",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "heroText": "Css动效学习",
        "tagline": "学习并收集好看的Css动画特效",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "好看至上",
            "details": "以常见的网页元素动画为标本，学习较为出彩的动画交互设计。"
          },
          {
            "title": "业务第一",
            "details": "根据常见的业务组件为蓝本，模仿热门的Css动效，以组件为单位，达到复制黏贴即可用。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-present Cheng Yu"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-3e0768c6",
      "path": "/"
    }
  ],
  "themeConfig": {}
}